version: '2'
services:
  app:
    container_name: dev-lamp-stack
    image: rvolt/apache2-php7-xdebug-phpunit:latest
    ports:
      - 4080:80
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    volumes:
      - ./www:/var/www/html:rw
    depends_on:
      - pma
  pma:
    container_name: dev-lamp-stack-pma
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=dev-lamp-stack-db
     - PMA_USER=dbuser
     - PMA_PASSWORD=dbuserpwd
    ports:
      - 4081:80
    links:
      - db
    depends_on:
      - db
    restart: 'no'
  db:
    container_name: dev-lamp-stack-db
    image: mysql:5.5
    ports:
      - 4082:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=sample_db  
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserpwd
    restart: 'no'
  test:
    container_name: dev-lamp-stack-test
    image: rvolt/apache2-php7-xdebug-phpunit:latest
    command: '/shared/watch.phpunit.sh -c specs/suite.xml'
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    volumes:
      - ./www:/var/www/html:rw
